### ISSUE TITLE
I used it in a list, it doesn't scroll

### ISSUE THREAD

**Issue by MineRala** [aheze/SwipeActions#24]
I used the SwipeAction library for the items in the list, this time the list does not scroll. I couldn't scroll because the cells were surrounded by SwipeAction. How can I solve the problem?
  List {
                        ForEach(lists) { list in
                            ZStack {
                                SwipeView {
                                    GroupListView(list: list)
                                        .background(Color.white)
                                        .cornerRadius(10)
                                        .shadow(radius: 5)
                                } trailingActions: {_  in
                                    editTrailingAction(for: list)
                                    deleteTrailingAction(for: list)
                                }
                                .swipeActionWidth(80)
                                NavigationLink(destination: ListView(products: list.products, title: list.title)) {
                                    EmptyView()
                                }.opacity(0.0)
                            }
                            .listRowBackground(Color.clear)
                            .listRowSeparator(.hidden)
                        }
                    }
                    .listStyle(.plain)

**Comment by iAmNaz** [comment]
Same issue here when I have a lot of list items that fills the scren.

**Comment by ngimelliUW** [comment]
Same thing - more generally in a scrollable view

**Comment by jacobcavin** [comment]
Anyone find a solution to this?

**Comment by chitraarasu** [comment]
@aheze Can you share any solution for this issue. Scroll not working

**Comment by chitraarasu** [comment]
Hi all, I got solution for this issue use .swipeActionWidth(50).

@jacobcavin @ngimelliUW @iAmNaz @MineRala

**Comment by serddmitry** [comment]
I've found that replacing a `highPriorityGesture` in the library with a simple `gesture` works better in a ScrollView. Also set `.swipeMinimumDistance(30)`.

**Comment by kenzo-ai** [comment]
> I've found that replacing a `highPriorityGesture` in the library with a simple `gesture` works better in a ScrollView. Also set `.swipeMinimumDistance(30)`.

Thanks, saved my life. 👍

**Comment by RobertDresler** [comment]
No need to replace gesture - just setting `. swipeMinimumDistance(24)` works for me.

**Comment by MineRala** [comment]
THANK YOU ALL.
