### ISSUE TITLE
Custom swipe actions in ScrollView

### ISSUE THREAD

**Issue by LulwahAlmisfer** [aheze/SwipeActions#29]
Custom swipe actions in SwiftUI’s ScrollView can prevent scrolling because the swipe gesture intercepts the scroll gesture, causing the ScrollView to lock and not scroll as expected

**Comment by umutbozdag** [comment]
How did you fix it?

**Comment by LulwahAlmisfer** [comment]
> How did you fix it?
"I've found that replacing a highPriorityGesture in the library with a simple gesture works better in a ScrollView. Also set .swipeMinimumDistance(30)." > 
https://github.com/aheze/SwipeActions/issues/24#issuecomment-2397815845
